### ISSUE TITLE
Implement object spawner

### ISSUE THREAD

**Issue by Foxxyyy** [CabooseSayzWTF/RDR1-Switch-and-PS4-Mod-Menu#2]
As you know I'm working on having custom models and I wish I could easily spawn just a few different props.
Could you implement that ? In the 'Spawner Options' submenu maybe?
I don't want to make external scripts for that...

**Comment by CabooseSayzWTF** [comment]
> As you know I'm working on having custom models and I wish I could easily spawn just a few different props. Could you implement that ? In the 'Spawner Options' submenu maybe? I don't want to make external scripts for that...

A very very very basic object spawner that spawns one prop at a time for foxxyyys needs has been created and gave to him directly. At this point in time it's unknown if i'll push a public update with a object spawner as it requires ALOT of work to be on par how I would personally want it to be and i'm not that great with the math for it tbh and switches vector3 data weirdness doesn't help the matter any however if it is to ever be added in the public repo it'll be after I finish the undead interior loader stuff.
