### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by unk0wn-u53r** [CabooseSayzWTF/RDR1-Switch-and-PS4-Mod-Menu#3]
Can you please create a version for the PC  Release of RDR, I don't know how to edit the *.wsc file.

Thank you!

**Comment by CabooseSayzWTF** [comment]
Menu was ported to wsc, then migrated to scripthook. We only maintain the scripthook version now, you can find it here: https://www.nexusmods.com/reddeadredemption/mods/184
